version: "3"
services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 // 도커 호스트 ip 수정 필요
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /home/temp/divolte-kafka-druid-superset/kafka

  # Divolte container
  divolte:
    image: godatadriven/divolte
    container_name: divolte
    environment:
      - DIVOLTE_KAFKA_BROKER_LIST=kafka:29092
    volumes:
      - ./conf/divolte/:/opt/divolte/divolte-collector/conf/
    ports:
      - 8290:8290
    depends_on:
      - kafka

  # Druid container
  druid:
    image: fokkodriesprong/docker-druid
    container_name: druid
    ports:
      - 8081:8081
      - 8082:8082
      - 8888:8888
    depends_on:
      - kafka

  # Superset container
  superset:
    image: amancevice/superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088

  # Superset container
  app:
    build: app/
    container_name: app
    ports:
      - 8090:8090

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/temp/divolte-kafka-druid-superset/mysql


  mysql-sink:
    image: mysql:8.0
    container_name: mysql-sink
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/temp/divolte-kafka-druid-superset/sinksql

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      -  /home/temp/divolte-kafka-druid-superset/postsql
